#server:
#  port: 8073
#  servlet:
#    context-path: /
#spring:
#  application:
#    name: deom
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    # ??????? ?????? ?????
#    druid:
#      driver-class-name: com.kingbase8.Driver
#      url: jdbc:kingbase8://172.16.30.131:54321/monitor_warn?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
#      username: system
#      password: HthtYjgl@889
#      #password: HthtYjgl@889
#      #???????
#      initial-size: 10
#      max-active: 100
#      min-idle: 10
#      # ?????????????
#      max-wait: 60000
#      # ??PSCache??????????PSCache???
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      # ???????????????????????????????
#      time-between-eviction-runs-millis: 60000
#      # ??????????????????????
#      min-evictable-idle-time-millis: 300000
#      #Oracle??????
#      #validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      stat-view-servlet:
#        enabled: true
#        url-pattern: /druid/*
#        #login-username: admin
#        #login-password: admin
#        allow:
#      filter:
#        stat:
#          log-slow-sql: true
#          slow-sql-millis: 1000
#          merge-sql: false
#        wall:
#          config:
#            multi-statement-allow: true
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  mvc:
#    format:
#      date: yyyy-MM-dd HH:mm:ss
#  servlet:
#    multipart:
#      #???
#      max-file-size: -1
#      #???
#      max-request-size: -1
#  #        group: microservices
## mybatis-plus????
#mybatis-plus:
#  # xml??????????????????? Mapper ???? XML ?????
#  mapper-locations: classpath*:**/*.xml
#  type-aliases-package: com.test.pojo
#  configuration:
#    # ??????????????:???????Java???????????
#    map-underscore-to-camel-case: true
#    # ??????????
#    cache-enabled: true
#    # ???????
#    lazy-loading-enabled: true
#    # ?????????sql?????????????????
#    #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    call-setters-on-nulls: true
#    # map???????0?????
